{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-perry
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/perry_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/perry/perry_{{ version }}.tar.gz
  sha256: d88e38a863a9846af68ce0a2856b0de2df400d07c35c81e574b23968584b7130

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=0.9.2
  run:
    - r-base
    - r-ggplot2 >=0.9.2

test:
  commands:
    - $R -e "library('perry')"           # [not win]
    - "\"%R%\" -e \"library('perry')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=perry
  license: GPL-2.0-or-later
  summary: Tools that allow developers to write functions for prediction error estimation with minimal programming effort and assist users with model selection in regression problems.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
